export default {
  bodega: "The building above has one primary purpose: to produce the highest quality software in reasonable time.\n\nMuch of the material going into that will be high-quality foodstuffs from around the world.\n\nMidguard, next door, is a \"President's Kitchen\" where, guests can order up whatever their heart desires & get it.\n\nThe building will run in terms of sprints. So, a developer gets an invitation for some period in the future.\n\nAt that point they pick dishes they might like to eat, drugs they might want to take, & people they might want to spend time with.\n\nThe system that coordinates those future needs and the desires of the present occupants is Argus.",
  kitchen: "Kitchens for the building and a pick-up counter.\n\nThe supply chain for everything is tracked and consumers are able to navigate a breakdown of the costs.\n\nThe software produced by the [DoH](//dhappy.org) is oriented toward ending war, homelessness, & hunger. Part of how this is acheived is through tithes that fill funding pools which can be used to suppliment purchaces.\n\nThe eventual goal is to get the pools filled to the point that hunger and homelessness go away along with the fear of them that looms over all our heads.",
  lounge: "Matela-based sitting/sleeping room w/ head shop. Door keyed to ids verfied through mail to a voter registration address.\n\nOne of the big issues is how to allow consumption without running afoul of draconian drug laws.\n\nThe concept at this point is to create the interfaces for collaboratively designing the building and livestreaming select sections of it.",
  bar: "A venue and bar. Door list uses purple alliance ids.\n\nPrimary concern is entertainment and testing an AI for [shared time](http://dhappy.org/.../calendar/fractal/).",
  'office space': "Coding workspaces and meeting places.\n\nSoftware foci include:\n\n* The toolset to write everything in. There is a huge ecosystem of software being developed in typescript that should be happening in ruby instead.\n\n* Much of the building is a testing-ground for various systems.\n\n+ Silver is responsible for procurement focusing on digitizing the supply chain, particularly with foodstuffs.",
  gym: "Gym.\n\n## Concomitant AI\n\n…",
  brothel: "A brothel.\n\nThe core desires to be pandered to are the artists and coders creating the product.\n\nPeople submit videos to apply for positions.\n\n",
  pharmacopia: "A pharmacopia.\n\nThe US has some system for sourcing drugs for research. That system is used to provision this section.\n\n## Concomitant AI\n\n…",
  hotel: "I envision a collection of maybe 20 primary and 100 ancilary open-source projects.\n\nTen of those accumulate ~5 person teams from around the globe who stay in these hotel rooms.\n\nDoors keyed using building ids.\n\nSome rooms are open to reservation online. All transactions are in IOTA.\n\nThis would need to be multiple floors.",
  park: "Space for animals w/ access to greenspace on the roof.",
}